name: foot_app
description: "Aplicación de comida con arquitectura limpia"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
    # Estado
  provider: ^6.1.5
    # Navegación
  go_router: ^14.6.2
    # HTTP
  http: ^1.5.0
  dio: ^5.7.0
    # Almacenamiento local
  shared_preferences: ^2.5.3
    # Utilidades
  equatable: ^2.0.7
  dartz: ^0.10.1
  intl: ^0.20.2
  image_picker: ^1.1.2
    #Visualizacion
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true



