name: foot_app
description: "Aplicaci√≥n de comida con arquitectura limpia"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  go_router: ^14.6.2
  http: ^1.5.0
  connectivity_plus: ^6.0.3
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  device_preview: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true